stages:
  - deploy

pip-package:
  stage: deploy
  image: python:3.9
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - pip install pdm
    - pdm config python.use_venv false
  script:
    - >
      pdm publish --verbose
      --username "__token__"
      --password "$PYPI_API_TOKEN"

pages:
  stage: deploy
  image: node:latest

  rules:
    - if: >
        ($CI_COMMIT_REF_NAME == "main"
        || $CI_COMMIT_REF_NAME == "gh-pages")
      changes:
        - docs/**/*
      when: always
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
  script:
    - npm install -g redoc-cli
    - redoc-cli bundle -o public/index.html docs/openapi.yaml
  artifacts:
    paths:
      - public
