repos:
  # Versioning: Commit Messages & Changelog
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.27.1
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # Autoupdate: Python code
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  # Autoformat: Python code
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--target-version=py39]

  # Autoformat: Python imports
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

  # Autoformat: YAML, JSON, Markdown, etc.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.1
    hooks:
      - id: prettier
        args:
          ["--ignore-unknown", "--no-error-on-unmatched-pattern", "!chart/**"]

  # Lint: Python
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ["--max-line-length=88"]
        exclude: ^(app/__version__.py|migrations)

  # Lint: Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint
        args: ["--fix", "--disable", "MD024"]
